export type Language = 'es' | 'en';
const es = {
  dog: 'Canino', cat: 'Felino', status: 'Atlas interactivo', tools: 'Herramientas', openTools: 'Abrir herramientas', closeTools: 'Cerrar herramientas', layers: 'Capas', views: 'Vistas', settings: 'Ajustes', species: 'Especie', region: 'Región anatómica', search: 'Buscar cualquier estructura...', isolate: 'Aislar', restore: 'Restaurar', zoomIn: 'Acercar', zoomOut: 'Alejar',
  portraitTitle: 'Gira tu dispositivo', portraitMessage: 'Para explorar mejor las estructuras, utiliza el teléfono en horizontal.', continuePortrait: 'Continuar en vertical', noModel: 'Modelo 3D no disponible', provisional: 'Información provisional', pending: 'Información pendiente', quality: 'Calidad gráfica', fontSize: 'Tamaño de letra', language: 'Idioma', left: 'Izquierda', right: 'Derecha', front: 'Craneal', back: 'Caudal', dorsal: 'Dorsal', ventral: 'Ventral', free: 'Libre', sagittal: 'Sagital', median: 'Mediano', transverse: 'Transversal', none: 'Sin corte', clippingNotice: 'El corte recorta la geometría disponible; no representa anatomía interna ni superficies de tejido.',
  skin: 'Piel', muscles: 'Músculos', tendons: 'Tendones', ligaments: 'Ligamentos', vessels: 'Vasos', nerves: 'Nervios', bones: 'Huesos', organs: 'Órganos', unavailable: 'Sin geometría disponible', section: 'Tejidos y estructuras', visual: 'Control de visualización', opacity: 'Opacidad', perspective: 'Perspectiva', anatomicalPlanes: 'Planos anatómicos', clipOffset: 'Posición del corte', customization: 'Personalización', interface: 'Interfaz', reading: 'Lectura de fichas', compact: 'Compacto', normal: 'Normal', large: 'Grande', extraLarge: 'Muy grande', high: 'Alta', balanced: 'Media', low: 'Baja', colors: 'Color libre de interfaz', chooseColor: 'Elegir cualquier color', hexColor: 'Código hexadecimal del tema', invalidColor: 'Utiliza un color hexadecimal de seis dígitos.', graphite: 'Grafito', forest: 'Bosque', violet: 'Noche violeta', terracotta: 'Terracota', sand: 'Arena clara', light: 'Claro', resetSettings: 'Restaurar apariencia', themeNotice: 'El visor mantiene un fondo más oscuro que la anatomía. Paneles, texto y botones ajustan automáticamente su contraste al color que elijas.', qualityNotice: 'Ajusta la resolución y los efectos del visor 3D.', layerNotice: 'Las capas sin geometría se habilitarán cuando existan modelos autorizados.',
  anatomy: 'Ficha anatómica', detail: 'Anatomía', images: 'Imágenes reales', sources: 'Fuentes', origin: 'Origen', insertion: 'Inserción', action: 'Acción / función', innervation: 'Inervación', relations: 'Relaciones anatómicas', closePanel: 'Cerrar ficha', openPanel: 'Abrir ficha', resetView: 'Reiniciar vista', view: 'Vista lateral', searchVoice: 'Buscar por voz', stopVoice: 'Detener grabación', listening: 'Escuchando…', fullBody: 'Cuerpo completo', head: 'Cabeza', torso: 'Tronco', limbs: 'Extremidades', translationNotice: 'Los contenidos veterinarios permanecen en español hasta disponer de traducción revisada.',
};
export type UiKey = keyof typeof es;
const en: Record<UiKey, string> = {
  dog: 'Canine', cat: 'Feline', status: 'Interactive atlas', tools: 'Tools', openTools: 'Open tools', closeTools: 'Close tools', layers: 'Layers', views: 'Views', settings: 'Settings', species: 'Species', region: 'Anatomical region', search: 'Search any anatomical structure...', isolate: 'Isolate', restore: 'Reset', zoomIn: 'Zoom in', zoomOut: 'Zoom out', portraitTitle: 'Rotate your device', portraitMessage: 'Use your phone in landscape to explore structures more comfortably.', continuePortrait: 'Continue in portrait', noModel: '3D model unavailable', provisional: 'Provisional information', pending: 'Information pending', quality: 'Graphics quality', fontSize: 'Font size', language: 'Language', left: 'Left', right: 'Right', front: 'Cranial', back: 'Caudal', dorsal: 'Dorsal', ventral: 'Ventral', free: 'Free', sagittal: 'Sagittal', median: 'Median', transverse: 'Transverse', none: 'No clipping', clippingNotice: 'Clipping trims the available geometry; it does not represent internal anatomy or tissue surfaces.', skin: 'Skin', muscles: 'Muscles', tendons: 'Tendons', ligaments: 'Ligaments', vessels: 'Vessels', nerves: 'Nerves', bones: 'Bones', organs: 'Organs', unavailable: 'No geometry available', section: 'Tissues and structures', visual: 'Visibility control', opacity: 'Opacity', perspective: 'Perspective', anatomicalPlanes: 'Anatomical planes', clipOffset: 'Clipping position', customization: 'Customization', interface: 'Interface', reading: 'Record reading', compact: 'Compact', normal: 'Normal', large: 'Large', extraLarge: 'Extra large', high: 'High', balanced: 'Balanced', low: 'Low', colors: 'Custom UI color', chooseColor: 'Choose any color', hexColor: 'Theme hexadecimal code', invalidColor: 'Use a six-digit hexadecimal color.', graphite: 'Graphite', forest: 'Forest', violet: 'Violet night', terracotta: 'Terracotta', sand: 'Light sand', light: 'Light', resetSettings: 'Reset appearance', themeNotice: 'The viewer keeps a darker background than the anatomy. Panels, text and buttons adjust their contrast to your chosen color.', qualityNotice: 'Adjusts the 3D viewer resolution and effects.', layerNotice: 'Layers without geometry will be enabled when authorized models are available.', anatomy: 'Anatomical record', detail: 'Anatomy', images: 'Real images', sources: 'Sources', origin: 'Origin', insertion: 'Insertion', action: 'Action / function', innervation: 'Innervation', relations: 'Anatomical relations', closePanel: 'Close record', openPanel: 'Open record', resetView: 'Reset view', view: 'Lateral view', searchVoice: 'Search by voice', stopVoice: 'Stop recording', listening: 'Listening…', fullBody: 'Full body', head: 'Head', torso: 'Torso', limbs: 'Limbs', translationNotice: 'Veterinary content remains in Spanish until a reviewed translation is available.',
};
export function t(language: Language, key: UiKey): string { return (language === 'en' ? en : es)[key]; }
